### ISSUE TITLE
Need information DNN testing

### ISSUE THREAD

**Issue by rajasekharponakala** [TRON15/lcj_MNIST#1]
Hi,

I need clarification from the paper. I have a GoogleNet (Caffe) DNN trained on a image classification task. Now, using  DeepXplore, how can i test model?

Thanks

**Comment by licj15** [comment]
We use Keras here. So the first thing you need to do is converting a Caffe Model to a Keras model. Keras usually use tensorflow as backend. So I suggest you to google "convert Caffe to tensorflow".
